:alien: Update CTCoreUnet to handle newer pytorch* library versions
Fix the following errors

- AttributeError: type object 'Trainer' has no attribute 'add_argparse_args' (need to change from Pytorch Lightning 1.0 to Lightning 2.0 style, see https://github.com/Lightning-AI/pytorch-lightning/issues/19905)
- ValueError: Cannot find 8ef2e2d423b67b53ec8113fc71a9b968bb0f66e7 in https://github.com/mateuszbuda/brain-segmentation-pytorch (change to use v1.0 tag)
- AttributeError: module 'torchmetrics' has no attribute 'IoU' (renamed to JaccardIndex, see https://github.com/Lightning-AI/torchmetrics/pull/662)

Also gitignoring __pycache__/ folder.