:recycle: Refresh code to work with 2024 library versions (#3)
* :memo: Add installation instructions and update Binder link

Some more getting started instructions to install the package, and updated the quickstart button from Pangeo Binder to regular Binder.

* :arrow_up: Bump pytorch and other dependencies

Upgrading pytorch, torchvision and other dependencies to newer versions in 2024. Simplified the conda environment.yml file to use conda-forge channel only and remove the md5 hash (put in the lock file instead). Not installing black and codecarbon as required dependencies anymore. Installing ONNX so model export will work.

* :alien: Update CTCoreUnet to handle newer pytorch* library versions

Fix the following errors

- AttributeError: type object 'Trainer' has no attribute 'add_argparse_args' (need to change from Pytorch Lightning 1.0 to Lightning 2.0 style, see https://github.com/Lightning-AI/pytorch-lightning/issues/19905)
- ValueError: Cannot find 8ef2e2d423b67b53ec8113fc71a9b968bb0f66e7 in https://github.com/mateuszbuda/brain-segmentation-pytorch (change to use v1.0 tag)
- AttributeError: module 'torchmetrics' has no attribute 'IoU' (renamed to JaccardIndex, see https://github.com/Lightning-AI/torchmetrics/pull/662)

Also gitignoring __pycache__/ folder.

* :arrow_up: Bump setup-miniconda from 2.1.1 to 3.0.4 and other Actions

Bumps [conda-incubator/setup-miniconda](https://github.com/conda-incubator/setup-miniconda) from 2.2.0 to 3.0.4.
- [Release notes](https://github.com/conda-incubator/setup-miniconda/releases)
- [Changelog](https://github.com/conda-incubator/setup-miniconda/blob/main/CHANGELOG.md)
- [Commits](https://github.com/conda-incubator/setup-miniconda/compare/v2.2.0...v3.0.4)

Also bumped actions/checkout from v2.3.4 to v4.2.2, and ubuntu from 20.04 to 24.04. Commented out `black` code quality check for now.

* :passport_control: Remove sha256 hashsum in explicit lockfile

Getting this error on CI: `ParseError: Could not parse explicit URL: https://conda.anaconda.org/conda-forge/linux-64/_libgcc_mutex-0.1-conda_forge.tar.bz2#fe51de6107f9edc7aa4f786a70f4a883943bc9d39b3bb7307c04c41410990726`. Try without the sha256 hashsum suffix to see if setup-miniconda works.

* :passport_control: Trust downloading UNet model from torch.hub.load

Assuming that mateuszbuda/brain-segmentation-pytorch is a trusted source to download the UNet model, so that Continuous Integration can work without a Y/N prompt.

* :mute: Only log to tensorboard if activated

Fix `AttributeError: 'ExperimentWriter' object has no attribute 'add_scalar'` by gating the `self.logger.experiment.add_scalar` call behind an if-condition. Logging can be activated if tensorboard is installed, and the `--logger=True` flag is passed via the command-line.

* :mag: Add teaser img of sediment core with IRD clasts to main README.md

Include a teaser image of a sediment core with Ice-Rafted Debris (IRD) clasts highlighted in red to the main README.md file. Also fixed a small typo.

* :pushpin: Use CUDA build of pytorch instead of CPU build

Re-created conda environment by running `CONDA_OVERRIDE_CUDA=12.6 conda env create --file=environment.yml --solver=libmamba` and re-locking with `conda list --explicit > environment-linux-64.lock`. Unsure why it's giving us CUDA 11.8 instead of CUDA 12, but oh well.